elements = [
        "ARRAY",
        "BAG",
        "BOOLEAN",
        "BINARY",
        "CONSTANT",
        "DERIVED ATTRIBUTE",
        "ENTITY",
        "ENTITY AS ATTRIBUTE",
        "ENUMERATION",
        "FUNTION",
        "INTEGER",
        "INVERSE",
        "LIST",
        "LOGICAL",
        "NUMBER",
        "PROCEDURE",
        "REAL",
        "REMARKS",
        "RULE",
        "SCHEMA",
        "SELECT",
        "SET",
        "STRING",
        "TYPE",
        "UNIQUE rule",
        "WHERE RULES"
        ]
